# Generated by Django 5.1.3 on 2024-11-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_First_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
