# Generated by Django 5.1.3 on 2024-11-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_First_App', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
